### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by ekerstein** [mmacpherson/tenforty#18]
First, thank you for making this package! I'm looking forward to using it.

I'm running into a problem during `pip install tenforty`.

I tried two environments to install this:
* Windows 10,  Python 3.12.2, pip 24.0
* Ubuntu 20.04.6 LTS, Python 3.9.10, pip 24.0

Error
---

```
pip install tenforty   
Collecting tenforty
  Using cached tenforty-2023.3.tar.gz (629 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "C:\Dropbox\Everything\Code\citycostcompare\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Dropbox\Everything\Code\citycostcompare\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Dropbox\Everything\Code\citycostcompare\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-d_oc8igm\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-d_oc8igm\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-d_oc8igm\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-d_oc8igm\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-d_oc8igm\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-d_oc8igm\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'tenforty/otslib/ots.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by mmacpherson** [comment]
Thanks kindly for the clear issue report @ekerstein , and sorry for the trouble.

1. Windows is not supported (yet):

- I will add this to the README in the Limitations section, and see if there's a badge I can add up top that shows this as well.
- There's no fundamental reason windows shouldn't work, but there's some package-discovery related issue that's causing the windows build to fail. I spent a couple hours on it in a windows virtualbox, and some flailings against the ci build are in the branch `does-windows-work` ([ref](https://github.com/mmacpherson/tenforty/tree/does-windows-work)), in case you might have better luck than I did. Would much appreciate any help here if this happens to be any area you know about.
- I would guess you'd be in business right away with WLS, or the Colab notebook, as potential workarounds for the time being.

2. Python 3.9 isn't currently supported.

3.10+ all are, and farther back interpreters could work, but I used some language features introduced in 3.10 in the package. It wouldn't be a big deal to unroll those if there was demand.

If it's easy for you to use a 3.10+ interpreter with your ubuntu setup, I think you'd be good to go.

I will close this issue, and create two new issues, one for the windows build and one for earlier interpreters.
