### ISSUE TITLE
Install error because of Cython dependencies?

### ISSUE THREAD

**Issue by didip** [mmacpherson/tenforty#44]
StackTrace:

```
pip install tenforty
Collecting tenforty
  Using cached tenforty-2023.3.tar.gz (629 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "/Users/didipkerabat/pf-manager/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/didipkerabat/pf-manager/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/didipkerabat/pf-manager/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/vk/pjdf7wj150v0cydrsc7cy3ch0000gn/T/pip-build-env-stn5r673/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/vk/pjdf7wj150v0cydrsc7cy3ch0000gn/T/pip-build-env-stn5r673/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/vk/pjdf7wj150v0cydrsc7cy3ch0000gn/T/pip-build-env-stn5r673/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 7, in <module>
        File "/private/var/folders/vk/pjdf7wj150v0cydrsc7cy3ch0000gn/T/pip-build-env-stn5r673/overlay/lib/python3.13/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ~~~~~~~~~~~~~~~~~~~~~^
              module_list,
              ^^^^^^^^^^^^
          ...<4 lines>...
              language=language,
              ^^^^^^^^^^^^^^^^^^
              aliases=aliases)
              ^^^^^^^^^^^^^^^^
        File "/private/var/folders/vk/pjdf7wj150v0cydrsc7cy3ch0000gn/T/pip-build-env-stn5r673/overlay/lib/python3.13/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
                      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/vk/pjdf7wj150v0cydrsc7cy3ch0000gn/T/pip-build-env-stn5r673/overlay/lib/python3.13/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'tenforty/otslib/ots.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Python version 3.13.1
OS: MacOS

**Comment by mmacpherson** [comment]
Thanks for this.

The CI rig currently tests 3.10, 3.11 and 3.12, but not 3.13.

I created a ticket around this, that should hopefully address the error you're getting: #45

**Comment by mmacpherson** [comment]
Hi @didip --

I did some updates today, that will hopefully have fixed this:

1. It builds 3.13 wheels for macos, so you will hopefully get a prebuilt wheel, and it won't try to compile it.
2. The files needed to compile the package are now included in the package, as a fallback.

I tested it with an m1 mac running Sonoma with python 3.13, and it worked for me.

If you like, please try the install again. If it doesn't work, lmk what macos version you've got?

**Comment by mmacpherson** [comment]
I think this is resolved now, feel free to re-open if it isn't. Thanks for the report.
